// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iboajumvexldonfrmuuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlib2FqdW12ZXhsZG9uZnJtdXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDAyNzksImV4cCI6MjA2MTA3NjI3OX0.x3IElColhOJHd1fLSRrS3pAv_L5WsrssNVH7Eg51jK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);